site_name: OpenGM API Documentation
docs_dir: docs
site_url: https://groupme-js.github.io/GroupMeCommunityDocs/
repo_url: https://github.com/groupme-js/GroupMeCommunityDocs
copyright: Copyright &copy; 2025 - OpenGM Project

site_description: "The OpenGM Project: Community GroupMe API documentation for all."

theme:
  name: material

  font:
    text: Mona Sans

  icon:
    logo: OpenGM/sprocket
    repo: fontawesome/brands/github

  favicon: assets/sprocket.svg

  code:
    highlight_theme: dracula

  custom_dir: src/overrides

  edit_uri: edit/master/docs

  extra_javascript:
    - assets/javascripts/hide-sidebar.js

  extra_css:
    - assets/stylesheets/extra.css

  features:
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.share
    - header.autohide
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - social
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: groupme-js/GroupMeCommunityDocs
      branch: master
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
      exclude_comitters:
        - web-flow

markdown_extensions:
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

nav:
  - Home: index.md
  - API Reference:
    - api/index.md
    - Webhook Bots: api/bots.md
    - WebSocket Gateway:
      - api/ws/websocket.md
      - Message Types: api/ws/messageTypes.md
    - Account Management: 
      - api/account/self.md
      - Contacts: api/account/contacts.md
      - Oauth/MFA: api/account/oauth.md
    - Groups:
      - api/groups/groups.md
      - Subgroups: api/groups/subgroups.md
      - Members: api/groups/members.md
      - Messages: api/groups/messages.md
      - Polls: api/groups/polls.md
      - Discovery: api/groups/directories.md
    - Direct Messages:
      - api/dms/dms.md
    - CDN:
      - Image Uploads: api/cdn/images.md
      - Video Uploads: api/cdn/video.md
      - File Uploads: api/cdn/files.md
    - Common Structures:
      - Message Attachments: api/common/attachments.md
      - Emoji Powerups: api/common/emoji.md
      - Message Events: api/common/events.md
    - Misc:
      - Emoji Reactions: api/misc/reactions.md
      - Calandar Events: api/misc/calendar.md
      - Image Galleries: api/misc/gallery.md
      - Pinning Messages: api/misc/pins.md
  - Examples:
    - examples/index.md
    - DinoBot: examples/dinobot.md
  - Contributing: contributing/index.md