site_name: OpenGM API Documentation
docs_dir: docs
site_url: https://groupme-js.github.io/GroupMeCommunityDocs/
repo_url: https://github.com/groupme-js/GroupMeCommunityDocs
copyright: Copyright &copy; 2025 - OpenGM Project

site_description: "The OpenGM Project: Community GroupMe API documentation for all."

# Custom Homepage Elements
home_cover_image: assets/sprocket.svg
home_tagline: GroupMe Community Docs
home_description: Community GroupMe API documentation for all.

home_gradient_hsla: hsla(160deg,47%,55%,1)

home_button1_name: API Reference
home_button1_url: api/
home_button1_theme: md-button md-button--primary                   
  
home_button2_name: Example Projects
home_button2_url: examples/
home_button2_theme: md-button

theme:
  name: material

  font:
    text: Mona Sans

  icon:
    logo: OpenGM/sprocket
    repo: fontawesome/brands/github

  favicon: overrides/assets/sprocket.svg

  code:
    highlight_theme: dracula

  custom_dir: src/overrides

  edit_uri: edit/master/docs

  features:
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.share
    - header.autohide
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - social
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: groupme-js/GroupMeCommunityDocs
      branch: master
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
      exclude_comitters:
        - web-flow

extra: 
  social:
    - icon: simple/groupme
      link: https://groupme.com/join_group/27317261/ibNNhx
    - icon: fontawesome/brands/github
      link: https://github.com/groupme-js/GroupMeCommunityDocs
    - icon: fontawesome/brands/discord
      link: https://discord.gg/5yxWtuuEZg

markdown_extensions:
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

nav:
  - Home: index.md
  - API Reference:
    - api/index.md
    - Webhook Bots: 
      - api/bots/index.md
    - WebSocket Gateway:
      - api/ws/index.md
      - Message Types: api/ws/messageTypes.md
    - Account Management: 
      - api/account/index.md
      - Contacts: api/account/contacts.md
      - Oauth/MFA: api/account/oauth.md
    - Groups:
      - api/groups/index.md
      - Subgroups: api/groups/subgroups.md
      - Members: api/groups/members.md
      - Messages: api/groups/messages.md
      - Polls: api/groups/polls.md
      - Discovery: api/groups/directories.md
      - Campus Directories: api/groups/campus.md
    - Direct Messages:
      - api/dms/index.md
    - Conversations:
      - api/conversations/index.md
      - Emoji Reactions: api/conversations/reactions.md
      - Calandar Events: api/conversations/calendar.md
      - Image Galleries: api/conversations/gallery.md
      - Pinning Messages: api/conversations/pins.md
    - Common Structures:
      - api/common/index.md
      - Message Attachments: api/common/attachments.md
      - Emoji Powerups: api/common/emoji.md
      - Message Events: api/common/events.md
    - CDN Management:
      - api/uploads/index.md
      - Image Uploads: api/uploads/images.md
      - Video Uploads: api/uploads/video.md
      - File Uploads: api/uploads/files.md
  - Examples:
    - examples/index.md
    - PingPong Bot: examples/pingpong.md
    - DinoBot: examples/dinobot.md
  - Contributing: 
    - contributing/index.md