site_name: OpenGM API Documentation
docs_dir: docs
site_url: https://alureonthevirus.github.io/GroupMeCommunityDocs/
repo_url: https://github.com/AlureonTheVirus/GroupMeCommunityDocs
copyright: Copyright &copy; 2025 - OpenGM Project

site_description: "The OpenGM Project: Community GroupMe API documentation for all."

theme:
  name: material
  icon:
    logo: OpenGM/sprocket
    repo: fontawesome/brands/github

  favicon: assets/sprocket.svg

  code:
    highlight_theme: dracula

  custom_dir: src/overrides

  edit_uri: edit/master/docs

  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.share
    - navigation.footer
    - content.code.copy
    - header.autohide
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - social
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: AlureonTheVirus/GroupMeCommunityDocs
      branch: main
      token: !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY"]

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
