site_name: OpenGM API Documentation
docs_dir: docs
site_url: https://groupme-js.github.io/GroupMeCommunityDocs/
repo_url: https://github.com/groupme-js/GroupMeCommunityDocs
copyright: Copyright &copy; 2025 - OpenGM Project

site_description: "The OpenGM Project: Community GroupMe API documentation for all."

theme:
  name: material

  font:
    text: Mona Sans

  icon:
    logo: OpenGM/sprocket
    repo: fontawesome/brands/github

  favicon: assets/sprocket.svg

  code:
    highlight_theme: dracula

  custom_dir: src/overrides

  edit_uri: edit/master/docs

  extra_css:
    - assets/stylesheets/extra.css

  features:
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.share
    - header.autohide
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - social
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: groupme-js/GroupMeCommunityDocs
      branch: master
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
      exclude_comitters:
        - web-flow

markdown_extensions:
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  homepage:
    hero_image: assets/sprocket.svg # Using your existing icon as the hero image
    tagline: "Community-driven documentation for GroupMe's Public API."
    buttons:
      - text: "Get Started"
        link: "/getting-started/" # Update with your actual link
        type: "brand" # 'brand' is the primary button style
      - text: "API Endpoints"
        link: "/api/endpoints/" # Update with your actual link
        type: "alt"
    features:
      - icon: "📚"
        title: "Comprehensive Endpoints"
        details: "Detailed documentation for every known GroupMe API endpoint, from messages to multimedia."
        link: "/api/endpoints/"
      - icon: "💻"
        title: "Code Samples"
        details: "Practical code examples in various languages to get you started quickly."
        link: "/examples/"
      - icon: "👥"
        title: "Community Driven"
        details: "Maintained and updated by the community. Contributions are always welcome!"
        link: "https://github.com/groupme-js/GroupMeCommunityDocs"
      - icon: "🛡️"
        title: "Type-Safe Models"
        details: "Clear data models and schemas for every API object, ensuring you know what to expect."
        link: "/api/models/"